<div class="pp-buttons-container">
    <button id="acodesh-customer-import" onclick="return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>
<span class="collect-indicator" id="acodesh_customer_import_collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>
<script>
require([
    'jquery',
    'prototype',
], function($){
	var collectSpan = jQuery('#acodesh_customer_import_collect_span');
    function Acodeshcustomerimport() {
        params = {
        };

        new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxCheckUrl() ?>', {
            loaderArea:     false,
            asynchronous:   true,
            parameters:     params,
            onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#collect_message_span').text('');
                },
            onSuccess: function(response) {
               // var response = JSON.parse(transport.responseText);
                collectSpan.find('.processing').hide();
 
                var resultText = '';
                if (response.status > 200) {
                    resultText = response.statusText;
                } else {
                    resultText = 'Products have been imported successfully';
                    collectSpan.find('.collected').show();
                }
                jQuery('#collect_message_span').text(resultText);

                var json = response.responseJSON;
                if (typeof json.time != 'undefined') {
                    jQuery('#row_mageworx_alsobought_general_collect_time').find('.value .time').text(json.time);
                }
            }
        });
    }
    $(document).ready(function($) {
	   	$("#acodesh-customer-import").on( "click", function() {	            
	        Acodeshcustomerimport();
	    });
    }); 
});
</script>