<div class="pp-buttons-container">
    <button id="customerimport" onclick="return false;">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>
<span class="collect-indicator" id="customer_collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="customerimp_collect_message_span">safdsf</span>
</span>
<script>
require([
    'jquery',
    'prototype',
], function($){
    var customercollectSpan = jQuery('#customer_collect_span');
    function customersyncronize() {
        params = {
        };

        new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxCheckUrl() ?>', {
            loaderArea:     false,
            asynchronous:   true,
            parameters:     params,
            onCreate: function() {
                customercollectSpan.find('.collected').hide();
                customercollectSpan.find('.processing').show();
                jQuery('#customerimp_collect_message_span').text('');
            },
            onSuccess: function(response) {
               // var response = JSON.parse(transport.responseText);
                customercollectSpan.find('.processing').hide();
 
                var resultText = '';
                if (response.status > 200) {

                    resultText = response.responseText;
                    resultText = 'Products have been imported successfully';
                } else {
                    resultText = 'Products have been imported successfully';
                    collectSpan.find('.collected').show();
                }
                jQuery('#customerimp_collect_message_span').html(resultText);

                var json = response.responseJSON;
                if (typeof json.time != 'undefined') {
                    jQuery('#row_mageworx_alsobought_general_collect_time').find('.value .time').text(json.time);
                }
            }
        });
    }
    $(document).ready(function($) {
        $("#customerimport").on( "click", function() {             
            customersyncronize();
        });
    }); 
});
</script>